-- ViralUp Studio: perfis, créditos, projetos e pagamentos.
-- Execute no SQL Editor do Supabase uma única vez.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  credits integer not null default 120 check (credits >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.projects (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tool text not null,
  provider text not null,
  provider_ref text,
  status text not null default 'queued',
  prompt text,
  aspect text,
  quality text,
  result_url text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  provider_payment_id text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  credits integer not null,
  amount numeric(12,2),
  status text,
  raw jsonb,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.payments enable row level security;

grant select on public.profiles to authenticated;
grant select on public.projects to authenticated;
revoke all on public.payments from anon, authenticated;

create policy "profiles read own" on public.profiles for select to authenticated using (auth.uid() = id);
create policy "projects read own" on public.projects for select to authenticated using (auth.uid() = user_id);

create or replace function public.consume_credits(p_user_id uuid, p_amount integer)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_amount <= 0 then return false; end if;
  update public.profiles
    set credits = credits - p_amount, updated_at = now()
  where id = p_user_id and credits >= p_amount;
  return found;
end;
$$;

create or replace function public.add_credits(p_user_id uuid, p_amount integer)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare new_balance integer;
begin
  if p_amount <= 0 then raise exception 'invalid amount'; end if;
  insert into public.profiles(id, credits) values (p_user_id, p_amount)
  on conflict (id) do update set credits = public.profiles.credits + excluded.credits, updated_at = now()
  returning credits into new_balance;
  return new_balance;
end;
$$;

revoke execute on function public.consume_credits(uuid, integer) from public, anon, authenticated;
revoke execute on function public.add_credits(uuid, integer) from public, anon, authenticated;
grant execute on function public.consume_credits(uuid, integer) to service_role;
grant execute on function public.add_credits(uuid, integer) to service_role;

-- Public media bucket for generated assets. Writes happen only through the server secret key.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('viralup-media', 'viralup-media', true, 524288000, array['image/webp','image/png','image/jpeg','video/mp4','video/webm','audio/mpeg','audio/wav'])
on conflict (id) do update set public = excluded.public;
